version: "3.8"
services:
  nginx-maqueta:
    image: nginx:stable-alpine
    container_name: nginx-maqueta
    restart: unless-stopped
    tty: true
    ports:
      - 80:80
      - 443:443
    volumes:
      - .:/var/www/html
      - ./infra/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
      - postgres-maqueta
      - redis-maqueta
    networks:
      - maquetanetwork

  postgres-maqueta:
    image: postgres:14-alpine
    container_name: postgres-maqueta
    restart: unless-stopped
    tty: true
    volumes:
      # - ./infra/postgres/data:/var/lib/postgresql/data #localpath
      - maqueta-db:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=homestead
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=homestead
    ports:
      - "5432:5432"
    networks:
      - maquetanetwork

  php:
    #uncomment this if you will use only docker compose
    build:
      context: "./infra/php/"
      dockerfile: Dockerfile
    container_name: php-maqueta
    restart: unless-stopped
    tty: true
    volumes:
      - .:/var/www/html
    ports:
      - 9000:80
    networks:
      - maquetanetwork

  redis-maqueta:
    image: redis:alpine
    container_name: redis-maqueta
    restart: unless-stopped
    tty: true
    volumes:
      - ./infra/redis/redis.conf:/usr/local/etc/redis/redis.conf # Mount the Redis configuration file
    networks:
      - maquetanetwork
    mem_limit: 2g

volumes:
  maqueta-db:
    driver: local

networks:
  maquetanetwork:
