name: CI

on:
  push:
    branches: ["develop"]
  pull_request:
    branches: ["develop"]

jobs:
  Build_and_check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Cache Docker layers
        uses: actions/cache@v3
        with:
          path: /var/lib/docker
          key: ${{ runner.os }}-docker-${{ hashFiles('**/Dockerfile') }}
          restore-keys: |
            ${{ runner.os }}-docker-

      - name: Cache Dockerfile
        uses: actions/cache@v3
        with:
          path: "./infra/php/" # Replace with the actual path to your Dockerfile
          key: ${{ runner.os }}-dockerfile-${{ hashFiles('./infra/php/') }}
          restore-keys: |
            ${{ runner.os }}-dockerfile-

      - name: Start Docker
        run: |
          docker-compose -f docker-compose-ci.yml up -d

      - name: Cache Composer dependencies
        uses: actions/cache@v3
        with:
          path: /vendor
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.json') }}
          restore-keys: |
            ${{ runner.os }}-composer-

      - name: Install dependencies
        run: |
          docker compose exec -T php composer install

      - name: Prepare Laravel Application
        run: |
          cp .env.example .env
          docker compose exec -T php php artisan key:generate
          docker compose exec -T php php artisan migrate

      # - name: Run code quality tools
      #   run: docker compose exec -T php ./vendor/bin/phpunit pint

      # - name: Run tests
      #   run: |
      #     docker-compose exec -T php php artisan test

      - name: Auto-merge to develop
        if: github.event.pull_request.merged == 'false' && github.event_name == 'pull_request' && github.ref == 'refs/heads/develop'
        uses: pascalgn/automerge-action@v0.15.6
        with:
          commit-message: "Auto-merged by GitHub Actions"
          merge-method: "squash" # O el método de merge que prefieras
          github-token: ${{ secrets.GITHUB_TOKEN }}
