name: CI

on:
  push:
    branches: ["develop"]
  pull_request:
    branches: ["develop"]

jobs:
  first_job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Cache Docker layers
        uses: actions/cache@v2
        with:
          path: /var/lib/docker
          key: ${{ runner.os }}-docker-${{ hashFiles('**/Dockerfile') }}
          restore-keys: |
            ${{ runner.os }}-docker-

      - name: Start Docker
        run: |
          docker compose up -d
          docker compose exec -T php php artisan migrate

      - name: Cache Composer dependencies
        uses: actions/cache@v2
        with:
          path: /root/.composer/cache
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.json') }}
          restore-keys: |
            ${{ runner.os }}-composer-

      - name: Install dependencies
        run: |
          docker compose exec -T php composer install

      - name: Prepare Laravel Application
        run: |
          cp .env.example .env
          docker compose exec -T php php artisan key:generate

      - name: Run code quality tools
        run: vendor/bin/phpunit pint

      # - name: Run tests
      #   run: |
      #     docker-compose exec -T php php artisan test

      - name: Auto-merge to develop
        if: github.event.pull_request.merged == 'false' && github.event_name == 'pull_request' && github.ref == 'refs/heads/develop'
        uses: pascalgn/automerge-action@v0.13.0
        with:
          commit-message: "Auto-merged by GitHub Actions"
          merge-method: "squash" # O el método de merge que prefieras
          github-token: ${{ secrets.GITHUB_TOKEN }}
